kafka:
  bootstrapAddress: 172.16.215.62:9092
  producer:
    id: 2
  topics:
    calls: test
    messages: test
generator:
  telephoneRandomCount: 7
  amountWordInMessage: 10
  dictionary: >
    Ashraf
    ashrafi
    ashram
    ashrama
    ashrams
    ash-staved
    ashstone
    bespew
    bespy
    bespice
    bespill
    bespin
    bespirit
    bespit
    besplash
    besplatter
    besplit
    bespoke
    bespoken
    bespot
    bespotted
    cicadas
    cycadean
    Cicadellidae
    cycadeoid
    Cycadeoidea
    cycadeous
    cicadid
    Cicadidae
    cycadiform
    cycadite
    cycadlike
    cycadofilicale
    dicarpellary
    dicast
    dicastery
    dicasteries
    dicastic
    dicasts
    dicatalectic
    dicatalexis
    gangman
    gangmaster
    gangplank
    gang-plank
    gangplanks
    gangplow
    gangplows
    gangrel
    gangrels
    gangrenate
    gangrene
    gangrened
    gangrenes
    half-armor
    half-ashamed
    half-ashamedly
    half-Asian
    Half-asiatic
    half-asleep
    half-assed
    half-awake
    halfback
    half-backed
    leaf-cutter
    leafdom
    leaf-eared
    leaf-eating
    leafed
    leafen
    leafer
    leafery
    leaf-footed
    leaf-forming
    leaf-fringed
    leafgirl
    leaf-gold
    leafhopper
    leaf-hopper
    misaligned
    misalignment
    misalignments
    misallegation
    misallege
    misalleged
    misalleging
    misally
    misalliance
    misalliances
    misallied
    misallies
    misallying
    misallocation
    misallot
    misallotment
    misallotted
    nonimbricated
    nonimbricately
    nonimbricating
    nonimbricative
    nonimitability
    nonimitable
    nonimitating
    nonimitation
    nonimitational
    nonimitative
    nonimitatively
    nonimitativeness
    nonimmanence
    nonimmanency
    nonimmanent
    nonimmanently
    nonimmateriality
    people-born
    peopled
    people-devouring
    peopledom
    peoplehood
    peopleize
    people-king
    peopleless
    people-loving
    peoplement
    people-pestered
    people-pleasing
    peopler
    peoplers
    Peoples
    protonate
    protonated
    protonation
    protone
    protonegroid
    protonema
    protonemal
    protonemata
    protonematal
    protonematoid
    protoneme
    Protonemertini
    protonephridial
    protonephridium
    protonephros
    protoneuron
    protoneurone
    protoneutron
    scegger
    scelalgia
    scelerat
    scelerate
    scelidosaur
    scelidosaurian
    scelidosauroid
    tokology
    tokologies
    tokoloshe
    tokomak
    tokomaks
    tokonoma
    tokonomas
    tokopat
    toktokje
    underpuller
    underput
    underqualified
    underqueen
    underquote
    underquoted
    underquoting
    underran
    underranger
    underrate
    underrated
    underratement
    underrates
    underrating
    underreach
    underread
    underreader
    underrealise
    underrealised
    underrealising
    underrealize
    underrealized
    underrealizing
    underrealm
    underream
    underreamer
    underreceiver
    underreckon
    underreckoning
    underrecompense
    underrecompensed
    underrecompensing
    underregion
    underregistration
    underrent
    underrented
    underrenting
    underreport
    underrepresent
    underrepresentation
    underrepresented
    underrespected
    underriddle
    underriding
    underrigged
    underring
    underripe
    underripened
    underriver
    underroarer
    underroast
    underrobe
    underrogue
    underroll
    underroller
    underroof
    underroom
    underroot
    underrooted
    Vira
    Viradis
    viragin
    viraginian
    viraginity
    viraginous
    virago
    viragoes
    viragoish
    viragolike
    viragos
    viragoship
    viral
    Virales
    virally
    virason
    Virbius
    Virchow
    Virden
    vire
    virelai
    virelay
    virelais
    virelays
    virement
    viremia
    viremias
    viremic
    Viren
    Virendra
    Vyrene
    virent
    vireo
    vireonine
    vireos
    vires
    virescence
    virescent
    Virg
    virga
    virgal
    virgas
    virgate
    virgated
    virgater
    virgates
    virgation
    whackers
    whacky
    whackier
    whackiest
    whacking
    whacko
    whackos
    whacks
    whaddie
    whafabout
    Whalan
    Whale
    whaleback
    whale-backed
    whalebacker
    whalebird
    whaleboat
    whaleboats
    whalebone
    whaleboned
